"""Bundle sample .mforge models into website/samples.js. Author: Vaishnavi.

Run from the repository root: python website/make_samples.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "ModelForge" / "review_2_core_implementation"
SAMPLES = [
    ("three_layer", "Three-layer network (all three optimisations)", ROOT / "samples" / "three_layer_demo.mforge"),
    ("iris", "Iris demo (fusion and dead code)", MODELS / "models" / "iris_demo.mforge"),
    ("binary", "Binary sigmoid classifier", MODELS / "models" / "binary_sigmoid_demo.mforge"),
    ("broken", "Broken model (shape error)", MODELS / "tests" / "fixtures" / "shape_mismatch.mforge"),
]
bundle = [{"id": key, "label": label, "text": path.read_text()} for key, label, path in SAMPLES]
(ROOT / "website" / "samples.js").write_text(
    "// Generated by website/make_samples.py (author: Vaishnavi).\n"
    "window.MODELFORGE_SAMPLES = " + json.dumps(bundle, indent=1) + ";\n")
print(f"wrote {len(bundle)} samples")
